### ISSUE TITLE
Remove support?

### ISSUE THREAD

**Issue by RazrFalcon** [programble/ego-tree#11]
What about nodes remove support? I understand that with a current architecture it's not really possible because it will invalidate `NodeId`, but what if I really-really have to remove a node?

UPD: I just noticed that you rewrote the whole thing...

**Comment by programble** [comment]
What does "remove" mean that detach doesn't cover? Dropping items could be done with `Tree<Option<T>>` or similar, but reclaiming storage in the Vec invalidates the entire tree.

**Comment by RazrFalcon** [comment]
Do'h. I missed it.

But what about `values()` iter? It will return detached nodes anyway (it doesn't matter for my case, but still).

**Comment by RazrFalcon** [comment]
>but reclaiming storage in the Vec invalidates the entire tree

You can store a list of free "nodes" so a new node will take a free space and will not expand the vector.

**Comment by programble** [comment]
Yeah `Values` and `Nodes` iterators can't really do anything about the structure of the tree.

Maintaining a free list really sounds like it would complicate the structure to the point where it would make sense to use a different tree representation.

**Comment by RazrFalcon** [comment]
I see. Then I'm closing it for now. I thought maybe this is a planned feature.
