### ISSUE TITLE
Why do you not use derive?

### ISSUE THREAD

**Issue by RazrFalcon** [programble/ego-tree#8]
It will simplify the code a lot.

**Comment by programble** [comment]
The non-derive implementations on `Tree` are to handle the `id`. The other ones, mostly on `NodeId`, are because the implementations don't actually depend on `T`. For example, the code has `impl<T> Clone for NodeId<T>`, but `#[derive(Clone)]` would generate `impl<T: Clone> Clone for NodeId<T>`.

**Comment by RazrFalcon** [comment]
I see. Makes sense.
